### ISSUE TITLE
help, please!

### ISSUE THREAD

**Issue by gajason** [JintaoLee-Roger/cigsegy#1]
Hi! It's very wonderful work! Thank u!
But I have some problems with compiling it in MSVS. And I need only a parser of SEG-Y file wrote in C++. 
Can u give me some help to understand how can I use your library?

Thank u in advance!

**Comment by JintaoLee-Roger** [comment]
I'm sorry, but I currently don't have a Windows computer, and I'm not familiar with MSVS either. However, all the dependency libraries are header-only, and the fmt library also has a header-only mode.

The code can be successfully compiled on g++ and clang++ compilers, so I believe it should be able to compile successfully using MSVS as well. However, I apologize that I'm currently unable to assist you in testing it on Windows.

**Comment by gajason** [comment]
Thank u very much for your reply! I'll continue to try!

**Comment by JintaoLee-Roger** [comment]
Hi! I have updated my code, which supports windows/MSVC now!

**Comment by gajason** [comment]
Thank u very much!!! That's great! Cheers!!
